#!/bin/bash

if [[ -z "$1" ]];
then
  echo "need problem number; ie '$0 52'"
  exit 1
fi

pid=`printf "p%03d" $1` # 52 -> p052

# could use 'cargo init --vcs none' but this removes '.gitignore'
# instead just init new project and remove .git directory

cargo init "$pid"
rm -rf "./$pid/.git"